permalink: pretty
markdown: maruku
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".ruby-version"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
url : http://railsgirls.jp

# user variables
title : Rails Girls Guide -Japanese-
tagline: Site Tagline
author :
  name : Yoko Harada
  email : yokolet@gmail.com
  github : railsgirls-jp
  twitter : username
  feedburner : feedname
comments :
  provider : disqus
  disqus :
    short_name : railsgirls-jp
