permalink: pretty
markdown: kramdown
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".ruby-version"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
url : http://railsgirls.jp
collections:
  blog:
    output: true
paginate_path: "blog/page:num"
plugins:
  - octopress-paginate
