permalink: pretty
markdown: kramdown
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".ruby-version"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
url : http://railsgirls.jp
defaults:
  -
    scope:
      path: ""
    values:
      hidden: true
  -
    scope:
      path: "_posts/blog"
    values:
      hidden: false
plugins:
  - jekyll-paginate
paginate_path: "/blog/page:num"
paginate: 15
