# jekyll settings
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock"]
pygments: true
permalink: pretty
markdown: redcarpet
safe: true
url : http://railsgirls.jp
lsi: false

# user variables
title : Rails Girls Guide -Japanese-
tagline: Site Tagline
author :
  name : Yoko Harada
  email : yokolet@gmail.com
  github : railsgirls-jp
  twitter : username
  feedburner : feedname
comments :
  provider : disqus
  disqus :
    short_name : railsgirls-jp
